name: root
description: A collection of useful dart packages

publish_to: none
repository: https://github.com/anurag-bharati/dart-packages


workspace:
  - packages/execution_policy

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

environment:
  sdk: ^3.6.0


