name: execution_policy
description: A Dart resilience and transient-fault-handling library inspired by C# Polly.
version: 0.2.0
repository: https://github.com/anurag-bharati/dart-packages
homepage: https://github.com/anurag-bharati/dart-packages/tree/main/
resolution: workspace
environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
